name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dotnet build
      uses: actions/setup-dotnet@v1
    - run: dotnet build
    - uses: actions/setup-node@v2
      with:
          node-version: '16'
    - name: Npm install and build      
      run: |
        cd DotnetTemplate.Web/
        npm install
        npm run build
    - name: Running Dotnet Tests
      run: dotnet test
    - name: Running Dotnet Tests
      run: |
        cd DotnetTemplate.Web/
        npm t
        npm run lint
